version: "3.7"
services:
  db:
    image: postgres
    container_name: database
    command:
      -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    networks:
      - my-network

  proxy-db:
    image: postgres
    container_name: proxy_database
    command:
      -p 5431
    expose:
      - 5431
    ports:
      - "5431:5431"
    env_file:
      - proxy/.env
    networks:
      - my-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  celery:
    build:
      context: ./proxy
    container_name: celery
    command: [ "/code/proxy/docker/celery.sh" ]
    volumes:
      - ./proxy/:/proxy
    depends_on:
      - redis
    networks:
      - my-network

  flower:
    build:
      context: ./proxy
    container_name: flower
    command: [ "/code/proxy/docker/flower.sh" ]
    ports:
      - "5555:5555"
    depends_on:
      - celery
    networks:
      - my-network


#  backend:
#    build:
#      context: ./backend
#    env_file:
#      - backend/src/.env
#    container_name: backend
#    ports:
#      - "8000:8000"
#    expose:
#      - 8000
#    depends_on:
#      - db
#    command: [ "/code/backend/docker/app.sh" ]
#    restart: on-failure
#    networks:
#      - my-network


networks:
  my-network:
    driver: bridge
