version: "3.7"
services:
  db:
    image: postgres
    container_name: database
    command:
      -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    networks:
      - my-network

  proxy-db:
    image: postgres
    container_name: proxy_database
    command:
      -p 5431
    expose:
      - 5431
    ports:
      - "5431:5431"
    env_file:
      - proxy/.env
    networks:
      - my-network

#  backend:
#    build:
#      context: ./backend
#    env_file:
#      - backend/src/.env
#    container_name: backend
#    ports:
#      - "8000:8000"
#    expose:
#      - 8000
#    depends_on:
#      - db
#    command: [ "/code/backend/docker/app.sh" ]
#    restart: on-failure
#    networks:
#      - my-network


networks:
  my-network:
    driver: bridge
