"""initial

Revision ID: 708c5910098c
Revises: 
Create Date: 2023-04-30 00:27:31.460176

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '708c5910098c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uid', sa.UUID(), nullable=False),
                    sa.Column('ip', sa.String(), nullable=False),
                    sa.Column('fingerprint', sa.JSON(), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
                    sa.Column('is_bot', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('uid')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
